use_sim_time: true
graph: iitb
priority_nodes: 2055461156 cluster_-172_5366445082
time_periods: 40.0 40.0
lambda_priority: 0.0
length_walk: 40
max_divisions: 10
eps_prob: 0
init_bots: 2
init_locations: ''
done: false
sim_length: 15000
discount_factor: 1
random_string: axv11
algo_name: v1