use_sim_time: true
graph: ladder
priority_nodes: gneJ11 gneJ17
time_periods: 40.0 40.0
lambda_priority: 0.0
length_walk: 80
max_divisions: 10
eps_prob: 0
init_bots: 1
init_locations: ''
done: false
sim_length: 15000
discount_factor: 1
random_string: axv33
algo_name: v1