use_sim_time: true
graph: iitb
priority_nodes: 4369058864 668672700
time_periods: 40.0 40.0
lambda_priority: 0.0
length_walk: 120
max_divisions: 10
eps_prob: 0
init_bots: 1
init_locations: ''
done: false
sim_length: 15000
discount_factor: 1
random_string: axv60
algo_name: v1