use_sim_time: true
graph: grid_5_5
priority_nodes: 2 23 16 19
time_periods: 60.0 60.0 60.0 60.0
lambda_priority: 10.0
length_walk: 60
max_divisions: 40
eps_prob: 0.1
init_bots: 4
init_locations: ''
done: false
sim_length: 30000
discount_factor: 1
random_string: exc19
algo_name: basic