use_sim_time: true
graph: grid_5_5
priority_nodes: 0 4 20 24
time_periods: 80.0 80.0 80.0 80.0
lambda_priority: 10.0
length_walk: 40
max_divisions: 40
eps_prob: 0.1
init_bots: 6
init_locations: ''
done: false
sim_length: 20000
discount_factor: 1
random_string: exp88
algo_name: basic